// Generates static/themes/<name>.css and src/lib/ui/themes.gen.ts from
// daisyUI's built-in themes (D-48). Each theme is its own small file, loaded
// only when someone picks it, so the default bundle doesn't grow.
//
// Every theme is tuned to WCAG 2.1 AA the same way our own themes are
// checked (NFR-14): semantic colours readable as text and on their soft
// tints, black or white text on coloured fills, secondary text at 4.5:1 and
// form-field borders at 3:1. Only lightness moves, and only where a theme
// falls short, so each theme keeps its character.
//
//   node scripts/gen-themes.mjs     (run after upgrading daisyUI)
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import themes from 'daisyui/theme/object.js';
import { hex, mix, ratio, readableOn, semantic, textOn } from '../src/lib/ui/colors.js';

const SEMANTIC = ['primary', 'secondary', 'accent', 'info', 'success', 'warning', 'error'];
// Categorical palette for groups and categories (app.css), light and dark variants.
const CAT = {
	light: ['#2a78d6', '#eb6834', '#1baf7a', '#eda100', '#e87ba4', '#008300', '#4a3aa7', '#e34948'],
	dark: ['#3987e5', '#d95926', '#199e70', '#c98500', '#d55181', '#008300', '#9085e9', '#e66767']
};

// The faintest mix of text into the page that still reaches min on both backgrounds.
function faintest(text, base100, base200, min, from) {
	for (let t = from; t <= 1.0001; t += 0.01) {
		const c = mix(text, base100, t);
		if (ratio(c, base100) >= min && ratio(c, base200) >= min) return hex(c);
	}
	return hex(text);
}

const version = JSON.parse(readFileSync('node_modules/daisyui/package.json', 'utf8')).version;
const NL = String.fromCharCode(10);
rmSync('static/themes', { recursive: true, force: true });
mkdirSync('static/themes', { recursive: true });

const list = [];
for (const name of Object.keys(themes).sort()) {
	const t = themes[name];
	const v = (k) => t['--color-' + k];
	const scheme = t['color-scheme'] === 'dark' ? 'dark' : 'light';
	const base100 = hex(v('base-100'));
	const base200 = hex(v('base-200'));
	const out = {};
	const text = readableOn(hex(v('base-content')), [base100, base200]);
	if (text.adjusted) out['base-content'] = text.color;
	const fixed = {};
	let tuned = false;
	for (const k of SEMANTIC) {
		const s = semantic(hex(v(k)), base100, base200);
		fixed[k] = s.color;
		if (s.adjusted) {
			out[k] = s.color;
			tuned = true;
		}
		if (s.adjusted || ratio(v(k + '-content'), s.color) < 4.5) out[k + '-content'] = s.content;
	}
	if (ratio(v('neutral-content'), v('neutral')) < 4.5) out['neutral-content'] = textOn(v('neutral'));
	out.muted = faintest(text.color, base100, base200, 4.5, 0.5);
	out.field = faintest(text.color, base100, base200, 3, 0.25);
	const decl = Object.entries(out).map(([k, c]) => `--color-${k}: ${c};`);
	CAT[scheme].forEach((c, i) => decl.push(`--cat-${i + 1}: ${c};`));
	const source = readFileSync(`node_modules/daisyui/theme/${name}.css`, 'utf8').trim();
	writeFileSync(
		`static/themes/${name}.css`,
		`/* daisyUI ${version} theme "${name}" with WCAG AA tuning (D-48). Generated by scripts/gen-themes.mjs; do not edit. */` + NL +
			source + NL + `[data-theme='${name}'] { ${decl.join(' ')} }` + NL
	);
	list.push({ name, scheme, tuned, base: base100, text: text.color, primary: fixed.primary, secondary: fixed.secondary, accent: fixed.accent, ...out });
}
writeFileSync(
	'src/lib/ui/themes.gen.ts',
	'// Generated by scripts/gen-themes.mjs from daisyUI ' + version + '; do not edit (D-48).' + NL +
		'// Preview colours for the theme picker, and the tuned values the contrast test checks.' + NL +
		'export type ThemeInfo = { name: string; scheme: "light" | "dark"; tuned: boolean; base: string; text: string; primary: string; secondary: string; accent: string } & Record<string, string | boolean>;' + NL +
		'export const DAISY_THEMES: ThemeInfo[] = ' + JSON.stringify(list, null, '\t') + ';' + NL
);
console.log(`${list.length} themes, ${list.filter((x) => x.tuned).length} tuned`);
